# Generated by Django 6.0.8 on 2026-09-21 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('garage', 'Garagem'), ('parking', 'Vaga'), ('warehouse', 'Galpão')], default='garage', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('hour', 'Hora'), ('day', 'Dia'), ('month', 'Mês')], default='month', max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('address_line', models.CharField(help_text='Endereço exato, não exibido publicamente.', max_length=180)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('covered', models.BooleanField(default=False)),
                ('electric_gate', models.BooleanField(default=False)),
                ('security_camera', models.BooleanField(default=False)),
                ('access_24h', models.BooleanField(default=False)),
                ('lighting', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('restroom', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='spaces/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_spaces', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='spaces.space')),
            ],
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['city', 'state'], name='spaces_spac_city_f4231c_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['space_type', 'is_active'], name='spaces_spac_space_t_40187d_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['price'], name='spaces_spac_price_8e4b62_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'space'), name='unique_user_space_favorite'),
        ),
    ]
