# Generated by Django 6.0.8 on 2026-09-25 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_space_accepted_vehicles_space_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='availability_checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='space',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Disponível'), ('negotiating', 'Em negociação'), ('rented', 'Alugado')], default='available', max_length=16),
        ),
        migrations.AddField(
            model_name='space',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='space',
            name='moderated',
            field=models.BooleanField(default=False, help_text='Oculta o anúncio por decisão da moderação.'),
        ),
        migrations.AddField(
            model_name='space',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('reply_phone', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='spaces.space')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Suspeita de fraude'), ('duplicate', 'Anúncio duplicado'), ('unavailable', 'Indisponível'), ('other', 'Outro')], max_length=20)),
                ('details', models.TextField(max_length=1000)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.PositiveSmallIntegerField(default=7)),
                ('instructions', models.TextField(help_text='Instruções de cobrança externa. Não inclua dados de clientes.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gt', 0), ('price__gt', 0)), name='positive_promotion_package')],
            },
        ),
        migrations.CreateModel(
            name='SavedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('space_type', models.CharField(blank=True, choices=[('garage', 'Garagem'), ('parking', 'Vaga'), ('warehouse', 'Galpão')], max_length=20)),
                ('billing_period', models.CharField(blank=True, choices=[('hour', 'Hora'), ('day', 'Dia'), ('month', 'Mês')], max_length=10)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'Visualização'), ('whatsapp', 'Clique WhatsApp'), ('phone', 'Clique telefone')], max_length=12)),
                ('visitor_hash', models.CharField(max_length=64)),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='spaces.space')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('space', 'kind', 'visitor_hash', 'day'), name='daily_listing_event')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.PositiveSmallIntegerField()),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento externo'), ('active', 'Ativado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('payment_reference', models.CharField(blank=True, help_text='Referência conferida pela administração; não armazene dados bancários sensíveis.', max_length=120)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='spaces.space')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaces.promotionpackage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('space',), name='one_pending_promotion_per_space')],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to='spaces.space')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('space', 'author'), name='one_service_review_per_author'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='service_review_score')],
            },
        ),
    ]
